# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everyone's Awesome
email: aj4ayushjain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Computer Science finalyear undergrad interested in tech. A bit crazy and lazy at times this is where i will try to  usually explain some tech or vent my feeling out.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aj4ayushjain.github.io/" # the base hostname & protocol for your site
twitter_username: Not-yet-available
github_username:  aj4ayushjain
linkedin_username: ayushjain0402

# Build settings
markdown: kramdown
